# Generated by Django 3.2.3 on 2021-07-16 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_roles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='username_p',
        ),
    ]
